### ISSUE TITLE
ImproperlyConfigured at / No shop!

### ISSUE THREAD

**Issue by bhaskar-c** [shoopio/shoop-gifter-demo#14]
Hi 

I am trying to run this demo.

Steps Taken
1) Downloaded shuup-gifter-demo, created virtual env, added shoop in a folder called shoop
2) pip install -r requirements.txt
3) python manage.py b2b_import_demo
4) (cd gifter && npm run build)
5) (cd shoop && npm run build)

All this commands execute without any error

Then I do 
python manage.py makemigrations
python manage.py migrate
python manage.py runserver

The server runs but when I visit localhost:8000 i get the following error:

> 
> ImproperlyConfigured
> No shop!
> /home/me/Desktop/shuup/shuup-gifter-demo-master/shoop/shoop/front/middleware.py in _set_shop, line 74
> /home/me/Desktop/shuup/shuup-gifter-demo-master/venv/bin/python 3.5.2
> 

The Django version in 1.8.19

Any ideas would be appreciated

**Comment by chessbr** [comment]
Hey @quakig you missed to run `python manage.py shuup_init`

**Comment by bhaskar-c** [comment]
@chessbr 
Thanks for that prompt reply.

I am a bit lost here. 
Firstly is it spelled Shoop or Shuup ?

**Comment by bhaskar-c** [comment]
Thanks I figured it out
